// authn/tanstack-start/src/routes/index.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  component: Home,
});

function Home() {
  const { identity } = Route.useRouteContext();
  return (
    <main>
      <h1>authdog authentication (TanStack Start)</h1>
      <p>
        This starter proves identity only. A signed-in session is not a
        permission grant.
      </p>
      {identity?.isAuthenticated ? (
        <p>
          Signed in as {identity.user?.emails?.[0]?.value}{" "}
          <a href="/api/logout">Sign out</a>
        </p>
      ) : (
        <p>
          Not signed in.{" "}
          {identity?.signinUri ? (
            <a href={identity.signinUri}>Sign in with the hosted Account portal</a>
          ) : (
            <span>
              Set <code>PK_AUTHDOG</code> in <code>.env</code>.
            </span>
          )}
        </p>
      )}
    </main>
  );
}

// authn/sveltekit/src/routes/+page.svelte
<script>
  import { page } from "$app/stores";

  const publicKey = import.meta.env.PUBLIC_AUTHDOG_PUBLIC_KEY;
  let signinUri = null;
  if (publicKey) {
    try {
      const payload = JSON.parse(
        atob(publicKey.replace("pk_", "")),
      );
      signinUri = `${payload.identityHost}/signin/${payload.environmentId}`;
    } catch {
      signinUri = null;
    }
  }
</script>

<main>
  <h1>authdog authentication (SvelteKit)</h1>
  <p>
    This starter proves identity only. A signed-in session is not a
    permission grant.
  </p>
  {#if signinUri}
    <p>
      <a href={signinUri}>Sign in with the hosted Account portal</a>
      {" · "}
      <a href="/profile">Profile</a>
    </p>
  {:else}
    <p>
      Set <code>PUBLIC_AUTHDOG_PUBLIC_KEY</code> in <code>.env</code> to a
      <code>pk_...</code> public key.
    </p>
  {/if}
</main>
